name: CI / CD for Dev
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install Dependencies
        run: yarn install

      - name: Build package
        run: yarn build

      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/front-app
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
          tag_with_ref: true
          tag_with_sha: true
          build_args: NODE_ENV=development
  deploy:
    name: Deploy

    needs: [build, test]

    runs-on: ubuntu-latest

    steps:
      - name: TODO
        run: echo not implemented..
